### ISSUE TITLE
Submit the updated index to Algolia during build.

### ISSUE THREAD

**Issue by cmarabate** [lukeocodes/netlify-plugin-algolia-index#1]
**Is your feature request related to a problem? Please describe.**
Not really, I just wish that there was a way to have this plugin also submit the index it creates during deployment to an index in my Algolia account automatically after it creates it.

**Describe the solution you'd like**
I'm imagining that I could edit the plugin to enter in the information needed to tell it which index on Algolia to submit it to and then it would be able to submit the new index to the specified index on Algolia right after it is created.

**Describe alternatives you've considered**
I've looked for other ways to automatically submit an index to Algolia on build but was not able to find anything that seemed like it would be easy to figure out.

I was hoping that I could use Zapier to connect Netlify & Algolia but Algolia is not available on there sadly.

**Comment by lukeocodes** [comment]
Thanks for raising this. I think it's a great idea and exactly what I need to do.

Currently, I have a Netlify function that finds the index file which is available publicly. But there is nothing to say we can't push to Algolia from the same plugin. 

I'm looking at this now, as the function-based export has become unreliable for me.

**Comment by cmarabate** [comment]
Sure thing! I'm glad you like the idea.

I have been just been manually visiting the index URL after I add anything to my site and copying all the json then pasting it into my Agolia index lol. This would make my life a lot easier =).

I look forward to whatever you come up with!

**Comment by chel-007** [comment]
Hello luke,, I tried using your plugin for my website,, I actually works great. I wanted to understand better how i can exclude particular files or folders from the indexing. In your setup you gave an example like this: 
[[plugins]]
  package = 'netlify-plugin-algolia-index'
    # all inputs is optional, we just show you the defaults below
    # [plugins.inputs]
      # exclude = ['/404.html'] # don't index this file
So,, then the 404.html should be excluded. I wanted to do this on multiple files. I tried something like this : # exclude = ['/404.html','downloads','blog','privacy','staff'] and after  downloading the json file at the generated url,, i uploaded it to algolia,, and I was still getting those excluded files in the search results. Perhaps the commas shouldn't be used as the separator? . I would be greatful if you can assist to achieve it . Thanks, chel

**Comment by lukeocodes** [comment]
> Hello luke,, I tried using your plugin for my website,, I actually works great. I wanted to understand better how i can exclude particular files or folders from the indexing. In your setup you gave an example like this:
> [[plugins]]
> package = 'netlify-plugin-algolia-index'
> # all inputs is optional, we just show you the defaults below
> # [plugins.inputs]
> # exclude = ['/404.html'] # don't index this file
> So,, then the 404.html should be excluded. I wanted to do this on multiple files. I tried something like this : # exclude = ['/404.html','downloads','blog','privacy','staff'] and after downloading the json file at the generated url,, i uploaded it to algolia,, and I was still getting those excluded files in the search results. Perhaps the commas shouldn't be used as the separator? . I would be greatful if you can assist to achieve it . Thanks, chel

Hi @Chel-Ash I've just replied to your message there :) Thanks!

**Comment by lukeocodes** [comment]
> **Is your feature request related to a problem? Please describe.**
> Not really, I just wish that there was a way to have this plugin also submit the index it creates during deployment to an index in my Algolia account automatically after it creates it.
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> I'm imagining that I could edit the plugin to enter in the information needed to tell it which index on Algolia to submit it to and then it would be able to submit the new index to the specified index on Algolia right after it is created.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> I've looked for other ways to automatically submit an index to Algolia on build but was not able to find anything that seemed like it would be easy to figure out.
> 
> I was hoping that I could use Zapier to connect Netlify & Algolia but Algolia is not available on there sadly.

Hey @cmarabate the latest release now exports directly to Algolia and it's a much better solution. Thanks for your suggestion :)
