### ISSUE TITLE
Increase parallelism

### ISSUE THREAD

**Issue by ehmicky** [lukeocodes/netlify-plugin-algolia-index#4]
Calls to `saveObjects()` [are done serially](https://github.com/lukeocodes/netlify-plugin-algolia-index/blob/6145128b67f74229848f55d99cfbdbcc2c5192ec/exporter/index.js#L24). Would it create a problem to perform them in parallel instead (for better performance)?

**Comment by lukeocodes** [comment]
Yeh this is a great question, which helps me simplify the code a bit too. Reduced the chunk to 10 records for testing

![image](https://user-images.githubusercontent.com/956290/85400153-e2c7a500-b54f-11ea-80b4-d187eacd6e1e.png)

**Comment by lukeocodes** [comment]
Changes in #8, let me know what you think

**Comment by ehmicky** [comment]
Looks great! :+1:
