### ISSUE TITLE
Top-level logic error handling

### ISSUE THREAD

**Issue by ehmicky** [lukeocodes/netlify-plugin-algolia-index#5]
The Algolia client is [created and initialized](https://github.com/lukeocodes/netlify-plugin-algolia-index/blob/6145128b67f74229848f55d99cfbdbcc2c5192ec/exporter/index.js#L8) on the top-level scope. If an error was thrown, it would not be properly handled as a user error (using `utils.build.failBuild()`).

Would it be possible to initialize it inside `onPostBuild()` instead, and add some error handling around it?

**Comment by lukeocodes** [comment]
Hey @ehmicky do you mind having a quick look at #7 and letting me know? Algolia is now wrapped in a trycatch. The promise `.catch` of saveObjects now throws the error out to that trycatch too, so they all meet `failPlugin`.

Is that an acceptable solution?

**Comment by ehmicky** [comment]
Yes, thanks!
I have added few comments in the PR.
